### ISSUE TITLE
ModuleNotFoundError: No module named 'rational'

### ISSUE THREAD

**Issue by liushuping0528** [xfflzl/CIM-CIL#1]

**Comment by liushuping0528** [comment]
Traceback (most recent call last):
  File "/content/CIM-CIL/main.py", line 4, in <module>
    from trainer import train
  File "/content/CIM-CIL/trainer.py", line 5, in <module>
    from utils import factory
  File "/content/CIM-CIL/utils/factory.py", line 1, in <module>
    from models.coil import COIL
  File "/content/CIM-CIL/models/coil.py", line 9, in <module>
    from utils.inc_net import IncrementalNet,CosineIncrementalNet,SimpleCosineIncrementalNet
  File "/content/CIM-CIL/utils/inc_net.py", line 5, in <module>
    from convs.resnet import resnet18# , resnet34, resnet50
  File "/content/CIM-CIL/convs/resnet.py", line 4, in <module>
    from rational.torch import Rational
ModuleNotFoundError: No module named 'rational'

**Comment by xfflzl** [comment]
Thanks for your interest in our work! Please install the package following its official [repo](https://github.com/ml-research/rational_activations) or simply by running `pip install rational-activations` in your Anaconda environment.
